# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Computer Stuff and Other Stuff
subtitle: By Sooham Rafiz
description: An exploration into algorithms. 
keywords:
  - algorithms
  - data structures
  - computer science
  - programming
  - software development
  - software engineering
  - software architecture
author: Sooham Rafiz
language: en
timezone: America/New_York

# Image settings
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
  mangle: true
  sanitize: true
  dompurify: false
  external_link: 
    enable: true
  descriptionLists: falsee

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://sooham.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# skip_render:
# paths that will be copied to public raw, without being rendered
# you can use glob exprs for path matching i.e mypage/**/*
skip_render: 
  - "source/**/*.js" # Javascript files will be copied to public folder

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: 
  enable: true # Open external links in new tab
  field: site
  exclude: ['www.sooham.github.io']

filename_case: 0
render_drafts: true
relative_link: false
future: true

highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

prismjs:
  enable: true
  preprocess: true
  line_number: false
  line_threshold: 0
  tab_replace: '    '
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 20
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: polk

mathjax:
  enable: true

#prism_plugin:
#  mode: 'realtime'    # realtime/preprocess
#  theme: 'dark'
#  line_number: true    # default false
#  #custom_css: 'path/to/your/custom.css'     # optional

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/sooham/sooham.github.io
  branch: master
  message: deploy changes to master {{ now('YYYY-MM-DD') }}

include:
exculde:
