# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Sooham Rafiz
subtitle:
description:
keywords:
author: Sooham Rafiz
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://sooham.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
# Where content to build is stored
source_dir: source
# where static site will be generated
public_dir: public
# tags directory
tag_dir: tags
# archive directory
archive_dir: archives
# category directory
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Prism syntax highlighting plugin
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'duotone-light'
  line_number: false    # default false

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: polk

# Include/Exclude Files and folders
exculde:
  - .DS_Store
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/sooham/sooham.github.io.git
  branch: master
